In [3]:
import pandas as pd
import numpy as np

In [42]:
dataset=pd.read_csv('lenses.txt',sep='\t',header=None)

In [43]:
dataset

0      1    2        3          4
0        young  myope   no  reduced  no lenses
1        young  myope   no   normal       soft
2        young  myope  yes  reduced  no lenses
3        young  myope  yes   normal       hard
4        young  hyper   no  reduced  no lenses
5        young  hyper   no   normal       soft
6        young  hyper  yes  reduced  no lenses
7        young  hyper  yes   normal       hard
8          pre  myope   no  reduced  no lenses
9          pre  myope   no   normal       soft
10         pre  myope  yes  reduced  no lenses
11         pre  myope  yes   normal       hard
12         pre  hyper   no  reduced  no lenses
13         pre  hyper   no   normal       soft
14         pre  hyper  yes  reduced  no lenses
15         pre  hyper  yes   normal  no lenses
16  presbyopic  myope   no  reduced  no lenses
17  presbyopic  myope   no   normal  no lenses
18  presbyopic  myope  yes  reduced  no lenses
19  presbyopic  myope  yes   normal       hard
20  presbyopic  hyper   no  reduced  no lenses
21  presbyopic  hyper   no   normal       soft
22  presbyopic  hyper  yes  reduced  no lenses
23  presbyopic  hyper  yes   normal  no lenses

In [44]:
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values

In [45]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
label_encode=LabelEncoder()
X

array([['young', 'myope', 'no', 'reduced'],
       ['young', 'myope', 'no', 'normal'],
       ['young', 'myope', 'yes', 'reduced'],
       ['young', 'myope', 'yes', 'normal'],
       ['young', 'hyper', 'no', 'reduced'],
       ['young', 'hyper', 'no', 'normal'],
       ['young', 'hyper', 'yes', 'reduced'],
       ['young', 'hyper', 'yes', 'normal'],
       ['pre', 'myope', 'no', 'reduced'],
       ['pre', 'myope', 'no', 'normal'],
       ['pre', 'myope', 'yes', 'reduced'],
       ['pre', 'myope', 'yes', 'normal'],
       ['pre', 'hyper', 'no', 'reduced'],
       ['pre', 'hyper', 'no', 'normal'],
       ['pre', 'hyper', 'yes', 'reduced'],
       ['pre', 'hyper', 'yes', 'normal'],
       ['presbyopic', 'myope', 'no', 'reduced'],
       ['presbyopic', 'myope', 'no', 'normal'],
       ['presbyopic', 'myope', 'yes', 'reduced'],
       ['presbyopic', 'myope', 'yes', 'normal'],
       ['presbyopic', 'hyper', 'no', 'reduced'],
       ['presbyopic', 'hyper', 'no', 'normal'],
       ['presbyopic

In [46]:
for i in range(len(X[0])):
    X[:,i]=label_encode.fit_transform(X[:,i])

In [47]:
X

array([[2, 1, 0, 1],
       [2, 1, 0, 0],
       [2, 1, 1, 1],
       [2, 1, 1, 0],
       [2, 0, 0, 1],
       [2, 0, 0, 0],
       [2, 0, 1, 1],
       [2, 0, 1, 0],
       [0, 1, 0, 1],
       [0, 1, 0, 0],
       [0, 1, 1, 1],
       [0, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 0],
       [1, 1, 0, 1],
       [1, 1, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 0],
       [1, 0, 0, 1],
       [1, 0, 0, 0],
       [1, 0, 1, 1],
       [1, 0, 1, 0]], dtype=object)

In [48]:
Y=label_encode.fit_transform(Y)

In [49]:
Y

array([1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 1, 1, 1, 1, 0, 1, 2, 1,
       1], dtype=int64)

In [50]:
onehot=OneHotEncoder(categorical_features=[0,1,2,3])

In [51]:
X=onehot.fit_transform(X).toarray()

In [52]:
X

array([[ 0.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.],
       [ 0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  1.],
       [ 0.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,  0.],
       [ 1.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0., 

In [54]:
from sklearn.cross_validation import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)

In [55]:
from sklearn.tree import DecisionTreeClassifier
clf_obj=DecisionTreeClassifier()
clf=clf_obj.fit(X_train,Y_train)

In [56]:
Y_pre=clf.predict(X_test)

In [57]:
Y_pre

array([1, 2, 0, 1, 0, 1, 1, 0], dtype=int64)

In [58]:
Y_test

array([1, 2, 1, 1, 1, 1, 1, 0], dtype=int64)

In [59]:
Y_train_pre=clf.predict(X_train)

In [60]:
Y_train_pre

array([1, 1, 1, 1, 2, 2, 1, 0, 0, 0, 1, 2, 1, 1, 1, 2], dtype=int64)

In [61]:
Y_train

array([1, 1, 1, 1, 2, 2, 1, 0, 0, 0, 1, 2, 1, 1, 1, 2], dtype=int64)

In [62]:
clf.feature_importances_

array([ 0.        ,  0.064     ,  0.        ,  0.10666667,  0.        ,
        0.336     ,  0.        ,  0.49333333,  0.        ])

In [63]:
clf.max_features_

9

In [64]:
clf.tree_

In [80]:
from sklearn.externals.six import StringIO
import pydotplus

In [81]:
from sklearn import tree
dot_data = StringIO()
tree.export_graphviz(clf,out_file=dot_data)

graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_png('xx.png')